name: GitHub pages build and deploy

on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - name: Shorten build times and decrease server load
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Jekyll build to target branch
      - name: Jekyll build to target branch (GitHub Pages)
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'master'
