name: Build and deploy Jekyll site to master

on:
  push:
    branches:
      - dev

jobs:
  Build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
      - uses: actions/checkout@v2
      - name: Deploy site to master
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: 'master'
